spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mls?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 19970819wy
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
server:
  port: 8989
